import { BaseEntity } from './../../shared';

const enum Region {
    'BRANCH',
    'CACHE',
    'CATCH',
    'CLOUD_RING',
    'COBALT_EDGE',
    'CURSE',
    'DEKLEIN',
    'DELVE',
    'DETORID',
    'ESOTERIA',
    'ETHERIUM_REACH',
    'FADE',
    'FEYTHABOLIS',
    'FOUNTAIN',
    'GEMINATE',
    'GREAT_WILDLANDS',
    'IMMENSEA',
    'IMPASS',
    'INSMOTHER',
    'MALPAIS',
    'OASA',
    'OMIST',
    'OUTER_PASSAGE',
    'PARAGON_SOUL',
    'PERIOD_BASIS',
    'PERRIGEN_FALLS',
    'PROVIDENCE',
    'PURE_BLIND',
    'QUERIOUS',
    'OUTER_RING',
    'SCALDING_PASS',
    'STAIN',
    'SYNDICATE',
    'TENAL',
    'TENERIFIS',
    'THE_KALEVALA_EXPANSE',
    'THE_SPIRE',
    'TRIBUTE',
    'VENAL',
    'VALE_OF_THE_SILENT',
    'WICKED_CREEK',
}

export class SolarSystem implements BaseEntity {
    constructor(
        public id?: string,
        public systemId?: number,
        public systemName?: string,
        public region?: Region,
        public trackPvp?: boolean,
        public trackRatting?: boolean,
    ) {
    }
}
