FROM openjdk:8-jdk-buster

RUN sed -i 's/deb.debian.org\/debian-security/archive.debian.org\/debian-archive\/debian-security/g' /etc/apt/sources.list
RUN sed -i 's/deb.debian.org\/debian/archive.debian.org\/debian-archive\/debian/g' /etc/apt/sources.list

RUN curl -sL https://deb.nodesource.com/setup_8.x | bash - && \
  apt-get update && \
  apt-get install -y nodejs=8.17.0-1nodesource1
