FROM ibm-semeru-runtimes:open-8-jdk-noble

SHELL ["/bin/bash", "-ec"]

RUN apt update && apt-get install xz-utils -y && apt-get install bzip2 -y

RUN curl -LO https://nodejs.org/dist/v8.17.0/node-v8.17.0-linux-x64.tar.xz && \
  tar -xvf node-v8.17.0-linux-x64.tar.xz && \
  cp -r node-v8.17.0-linux-x64/{bin,include,lib,share} /usr/

RUN npm install --global yarn
